name: Build and Run tests

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci  

      - name: Setup environment variables
        run: | 
          touch .env
          echo "DB_URI=${{ secrets.DB_URI }}" >> .env

      - name: Build and run
        run: npm run test
